# Generated by Django 3.0.14 on 2024-02-02 08:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('national_code', models.IntegerField(unique=True)),
                ('address', models.CharField(max_length=255)),
                ('contact_person', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='PhoneNumber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=20)),
                ('phone_type', models.CharField(choices=[('Mobile', 'Mobile'), ('Work', 'Work'), ('Home', 'Home')], default='Mobile', max_length=6)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('national_code', models.IntegerField(unique=True)),
                ('phone_number', models.ForeignKey(blank=True, choices=[('Mobile', 'Mobile'), ('Work', 'Work'), ('Home', 'Home')], null=True, on_delete=django.db.models.deletion.CASCADE, to='Clients_and_Contacts.PhoneNumber')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(null=True)),
                ('detail', models.TextField(null=True)),
                ('client_offered', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offered_contact', to='Clients_and_Contacts.Client')),
                ('client_requested', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requested_contact', to='Clients_and_Contacts.Client')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Clients_and_Contacts.Employee')),
            ],
        ),
    ]
