# Generated by Django 5.0.1 on 2024-02-03 11:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('national_code', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('address', models.CharField(max_length=255)),
                ('phone_number', models.CharField(max_length=64)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('client_details', models.TextField(null=True)),
                ('username', models.CharField(max_length=64)),
                ('password', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=64)),
                ('last_name', models.CharField(max_length=64, null=True)),
                ('national_code', models.IntegerField(unique=True)),
                ('phone_number', models.IntegerField(unique=True)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('employee_details', models.TextField(null=True)),
                ('username', models.CharField(max_length=64)),
                ('password', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(null=True)),
                ('detail', models.TextField(null=True)),
                ('Client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Clients_and_Contacts.client')),
            ],
        ),
    ]
