# Generated by Django 3.0.14 on 2024-02-02 08:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Clients_and_Contacts', '0001_initial'),
        ('Estates_and_Locations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='estate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Estates_and_Locations.Estate'),
        ),
        migrations.AddField(
            model_name='client',
            name='phone_number',
            field=models.ForeignKey(blank=True, choices=[('Mobile', 'Mobile'), ('Work', 'Work'), ('Home', 'Home')], null=True, on_delete=django.db.models.deletion.CASCADE, to='Clients_and_Contacts.PhoneNumber'),
        ),
        migrations.AddField(
            model_name='client',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
