# Generated by Django 3.0.14 on 2024-02-03 10:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Estates_and_Locations', '0001_initial'),
        ('Clients_and_Contacts', '0002_contact_estate'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('details', models.TextField(null=True)),
                ('number_of_invoices', models.IntegerField()),
                ('payment_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fee_percentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('fee_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date_signed', models.DateField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Clients_and_Contacts.Client')),
            ],
        ),
        migrations.CreateModel(
            name='Contract_type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contract_type', models.CharField(max_length=64)),
                ('fee_percentage', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='Payment_frequency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_frequency_name', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction_type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type_name', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Under_contract',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Contracts_and_Transactions.Contract')),
                ('estate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Estates_and_Locations.Estate')),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('details', models.TextField(null=True)),
                ('client_offered', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offered_transactions', to='Clients_and_Contacts.Client')),
                ('client_requested', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requested_transactions', to='Clients_and_Contacts.Client')),
                ('transaction_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Contracts_and_Transactions.Transaction_type')),
            ],
        ),
        migrations.CreateModel(
            name='Contract_invoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(max_length=64)),
                ('invoice_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('details', models.TextField(null=True)),
                ('date_created', models.DateField()),
                ('billing_date', models.DateField()),
                ('date_paid', models.DateField()),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Contracts_and_Transactions.Contract')),
            ],
        ),
        migrations.AddField(
            model_name='contract',
            name='contract_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Contracts_and_Transactions.Contract_type'),
        ),
        migrations.AddField(
            model_name='contract',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Clients_and_Contacts.Employee'),
        ),
        migrations.AddField(
            model_name='contract',
            name='estate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Estates_and_Locations.Estate'),
        ),
        migrations.AddField(
            model_name='contract',
            name='payment_frequency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Contracts_and_Transactions.Payment_frequency'),
        ),
        migrations.AddField(
            model_name='contract',
            name='transaction_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Contracts_and_Transactions.Transaction'),
        ),
    ]
